services:
    api:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        user: "1000:1000"
        ports:
            - 3000:3000
        networks:
            - app-network
        depends_on:
            - db
        environment:
            DATABASE_URL: postgres://root:root@db:5432/notalone
        volumes:
            - ./backend:/app

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: notalone
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_INITDB_ARGS: "--data-checksums"
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d 
        ports:
            - 5434:5432
        networks:
            - app-network

volumes:
    db-data:

networks:
    app-network: