version: "3"
services:
    frontend:
        environment:
                - EXPO_PUBLIC_IP=192.168.1.155
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        ports:
            - 8081:8081
            - 19000:19000
        networks:
            - app-network
        volumes:
            - ./frontend:/app
            - /app/node_modules

    api:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - app-network
        depends_on:
            - db
        environment:
            DATABASE_URL: postgres://root:root@db:5432/notalone
        volumes:
            - ./backend:/app
            - /app/node_modules

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: notalone
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_INITDB_ARGS: "--data-checksums"
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d 
        ports:
            - 5434:5432
        networks:
            - app-network

volumes:
    db-data:

networks:
    app-network:
