import { QueryInterface, DataTypes } from "sequelize";
import { v4 as uuidv4 } from "uuid";

export default {
    async up(queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
      const now = new Date();
        await queryInterface.createTable("natures", {
          id_nature: {
            type: DataTypes.UUID,
            primaryKey: true,
            allowNull: false,
            defaultValue: DataTypes.UUIDV4,
          },
          name: {
            type: DataTypes.STRING,
            allowNull: false,
          },
          type: {
            type: DataTypes.ENUM("tree","flower"),
            allowNull: false,
          },
            url: {
            type: DataTypes.STRING,
            allowNull: false,
          },
          created_at: {
            type: DataTypes.DATE,
            allowNull: false,
        },
        updated_at: {
            type: DataTypes.DATE,
            allowNull: false,
        },
        });
        await queryInterface.bulkInsert("natures", [
        {
            id_nature: uuidv4(),
            name: "1",
            type: "tree",
            url:"/static/forest/trees/1.svg" ,
            created_at: now,
            updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "2",
          type: "tree",
          url:"/static/forest/trees/2.svg" ,
          created_at: now,
          updated_at: now,
        },{
          id_nature: uuidv4(),
          name: "3",
          type: "tree",
          url:"/static/forest/trees/3.svg" ,
          created_at: now,
          updated_at: now,
        },{
          id_nature: uuidv4(),
          name: "4",
          type: "tree",
          url:"/static/forest/trees/4.svg" ,
          created_at: now,
          updated_at: now,
        },{
          id_nature: uuidv4(),
          name: "5",
          type: "tree",
          url:"/static/forest/trees/5.svg" ,
          created_at: now,
          updated_at: now,
        },{
          id_nature: uuidv4(),
          name: "6",
          type: "tree",
          url:"/static/forest/trees/6.svg" ,
          created_at: now,
          updated_at: now,
        },{
          id_nature: uuidv4(),
          name: "7",
          type: "tree",
          url:"/static/forest/trees/7.svg" ,
          created_at: now,
          updated_at: now,
        },{
          id_nature: uuidv4(),
          name: "8",
          type: "tree",
          url:"/static/forest/trees/8.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "1",
          type: "flower",
          url:"/static/forest/flowers/1.svg" ,
          created_at: now,
          updated_at: now,
          },
          {
            id_nature: uuidv4(),
            name: "2",
            type: "flower",
            url:"/static/forest/flowers/2.svg" ,
            created_at: now,
            updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "3",
          type: "flower",
          url:"/static/forest/flowers/3.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "4",
          type: "flower",
          url:"/static/forest/flowers/4.svg" ,
          created_at: now,
          updated_at: now,
      },
      {
        id_nature: uuidv4(),
        name: "5",
        type: "flower",
        url:"/static/forest/flowers/5.svg" ,
        created_at: now,
        updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "6",
          type: "flower",
          url:"/static/forest/flowers/6.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "7",
          type: "flower",
          url:"/static/forest/flowers/7.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "8",
          type: "flower",
          url:"/static/forest/flowers/8.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "9",
          type: "flower",
          url:"/static/forest/flowers/9.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "10",
          type: "flower",
          url:"/static/forest/flowers/10.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "11",
          type: "flower",
          url:"/static/forest/flowers/11.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "12",
          type: "flower",
          url:"/static/forest/flowers/12.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "13",
          type: "flower",
          url:"/static/forest/flowers/13.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "14",
          type: "flower",
          url:"/static/forest/flowers/14.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "15",
          type: "flower",
          url:"/static/forest/flowers/15.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "16",
          type: "flower",
          url:"/static/forest/flowers/16.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "17",
          type: "flower",
          url:"/static/forest/flowers/17.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "18",
          type: "flower",
          url:"/static/forest/flowers/18.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "19",
          type: "flower",
          url:"/static/forest/flowers/19.svg" ,
          created_at: now,
          updated_at: now,
        },
        {
          id_nature: uuidv4(),
          name: "20",
          type: "flower",
          url:"/static/forest/flowers/20.svg" ,
          created_at: now,
          updated_at: now,
        },

    ]);
  },

  async down(queryInterface: QueryInterface) {
    await queryInterface.dropTable("natures");
},
};
