import { QueryInterface, DataTypes } from "sequelize";
import { v4 as uuidv4 } from "uuid";

export default {
	async up(queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
		const now = new Date();
		await queryInterface.createTable("natures", {
			id_nature: {
				type: DataTypes.UUID,
				primaryKey: true,
				allowNull: false,
				defaultValue: DataTypes.UUIDV4,
			},
			name: {
				type: DataTypes.STRING,
				allowNull: false,
			},
			type: {
				type: DataTypes.ENUM("tree", "flower"),
				allowNull: false,
			},
			points: {
				type: DataTypes.INTEGER,
				allowNull: false,
			},
			url: {
				type: DataTypes.STRING,
				allowNull: false,
			},
			created_at: {
				type: DataTypes.DATE,
				allowNull: false,
			},
			updated_at: {
				type: DataTypes.DATE,
				allowNull: false,
			},
		});
		await queryInterface.bulkInsert("natures", [
			{
				id_nature: uuidv4(),
				name: "1",
				type: "tree",
				url: "/static/forest/trees/1.svg",
				points: 20,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "2",
				type: "tree",
				url: "/static/forest/trees/2.svg",
				points: 20,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "3",
				type: "tree",
				url: "/static/forest/trees/3.svg",
				points: 20,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "4",
				type: "tree",
				url: "/static/forest/trees/4.svg",
				points: 25,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "5",
				type: "tree",
				url: "/static/forest/trees/5.svg",
				points: 25,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "6",
				type: "tree",
				url: "/static/forest/trees/6.svg",
				points: 25,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "7",
				type: "tree",
				url: "/static/forest/trees/7.svg",
				points: 30,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "8",
				type: "tree",
				url: "/static/forest/trees/8.svg",
				points: 30,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "1",
				type: "flower",
				url: "/static/forest/flowers/1.svg",
				points: 20,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "2",
				type: "flower",
				url: "/static/forest/flowers/2.svg",
				points: 20,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "3",
				type: "flower",
				url: "/static/forest/flowers/3.svg",
				points: 20,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "4",
				type: "flower",
				url: "/static/forest/flowers/4.svg",
				points: 20,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "5",
				type: "flower",
				url: "/static/forest/flowers/5.svg",
				points: 25,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "6",
				type: "flower",
				url: "/static/forest/flowers/6.svg",
				points: 25,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "7",
				type: "flower",
				url: "/static/forest/flowers/7.svg",
				points: 25,
				created_at: now,
				updated_at: now,
			},
			{
				id_nature: uuidv4(),
				name: "8",
				type: "flower",
				url: "/static/forest/flowers/8.svg",
				points: 25,
				created_at: now,
				updated_at: now,
			},
		]);
	},

	async down(queryInterface: QueryInterface) {
		await queryInterface.dropTable("natures");
	},
};
